### ISSUE TITLE
Storage amount is not correct

### ISSUE THREAD

**Issue by SoupDaGlu** [elementary/switchboard-plug-about#129] opened 2020-07-22 08:03 UTC
I set aside 256 GB of storage for elementary OS, but here is it showing only 20 GB. How can I fix this?
![Screenshot from 2020-07-22 11-59-31](https://user-images.githubusercontent.com/31928459/88150731-d304b480-cc12-11ea-9b3d-02b481ae3d46.png)
Note: I initially had Windows as my OS, and I installed elementary OS as a dual boot. I put /swap partition to be 16 GB, / partition to be 20 GB, and /home to be the rest of space I had left.

**Comment by danrabbit** [comment] 2020-07-23 19:16
Closing as a duplicate of #119

**Closed by danrabbit** 2020-07-23 19:16 UTC
