### ISSUE TITLE
Geforce GTX 1080 Ti not showing up in about info.

### ISSUE THREAD

**Issue by Bolos46** [elementary/switchboard-plug-about#89] opened 2019-04-26 20:07 UTC
```
$ neofetch
OS: elementary OS 5.0 Juno x86_64 
Host: Z87X-UD5H 
Kernel: 4.15.0-48-generic 
Packages: 1728 
Shell: bash 4.4.19 
DE: Pantheon 
WM: Mutter(Gala) 
Terminal: io.elementary.t 
CPU: Intel i7-4770K (8) @ 3.900GHz 
GPU: NVIDIA GeForce GTX 770 
Memory: 2476MiB / 32121MiB 
```

```
$ sudo lshw -c video
*-display
      description: VGA compatible controller
      product: GK104 [GeForce GTX 770]
      vendor: NVIDIA Corporation
      physical id: 0
      bus info: pci@0000:01:00.0
      version: a1
      width: 64 bits
      clock: 33MHz
      capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
      configuration: driver=nvidia latency=0
      resources: irq:35 memory:f2000000-f2ffffff memory:e8000000-efffffff memory:f0000000-f1ffffff ioport:e000(size=128) memory:c0000-dffff
```
I just plugged a GTX 1080 Ti on top of my GTX 770 (with screen connected on the 770) and even if fans and light are running on the 1080, it doesn't seem to be recognized.

I'd like to use the two cards for 3D rendering.

I just installed Elementary but had the same problem on macOS (hackintosh).

**Comment by peteruithoven** [comment] 2019-04-26 20:39
Looking at `lshw` the gpu isn't found in general. I'm afraid the issue isn't just that the about page doesn't show the info. So I'm closing the issue. 
I'd recommend doing research on how people on a comparable OS like Ubuntu use the GTX 1080 Ti and utilize multiple gpu's. Maybe check what happens when you only use the GTX 1080 Ti.

**Closed by peteruithoven** 2019-04-26 20:39 UTC
