### ISSUE TITLE
Boot menu timeout cannot be changed

### ISSUE THREAD

**Issue by diddy-boy** [elementary/switchboard-plug-about#216] opened 2021-05-28 19:41 UTC
## What Happened

The boot screen has too long a timeout (30 seconds).
Attempting to chnage this with efibootmgr claims it has updated the boot menu but has not changed the boot timeout.

## Expected Behavior

A boot timeout of up to 5 seconds would be a nice timeout allowing the user to select a boot option or not.
30 seconds is too long

## Steps to Reproduce

1.
2.
3.

**Comment by m4st3r-bl4ckb1rd** [comment] 2021-08-17 12:14
Could be related to what i was facing. Kernel updates where not reflected to boot.
the root cause was that /boot/grub/grub.cfg was not copied to /boot/efi/EFI/ubuntu/grub/grub.cfg

i found this solution [here](https://elementaryos.stackexchange.com/questions/28013/new-kernel-boot-option-not-showing-up-in-grub/28118#28118)

**Comment by ryonakano** [comment] 2024-06-19 11:56
Closing as a duplicate of https://github.com/elementary/triage/issues/109

**Closed by ryonakano** 2024-06-19 11:56 UTC
