### ISSUE TITLE
Make the "Check for Update" button launch AppCenter on the "Updates" section.

### ISSUE THREAD

**Issue by SubhadeepJasu** [elementary/switchboard-plug-about#42] opened 2017-09-21 17:18 UTC
The "Check for Updates" button in the about plug in Loki doesn't seem to do anything when clicked. It would be better to make it launch AppCenter and also to the updates section directly.

**Comment by codygarver** [comment] 2017-09-21 17:19
Duplicate of #41.

**Closed by codygarver** 2017-09-21 17:19 UTC

**Comment by SubhadeepJasu** [comment] 2017-09-21 17:23
OK
